function [ys_, params, info] = nk3_ex4_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=1;
    ys_(5)=1;
    ys_(2)=1.005;
    ys_(1)=1;
    ys_(3)=ys_(2)/params(5);
    % Auxiliary equations
    check_=0;
end
